name: Rudolf Kroseberg
favicon: null
layout_spectrum: 0.2194974492304027
typography_spectrum: 0.8360552079975605
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.09890040941536427
  lightness: 0.2905015889555216
  saturation: 0.27608607639558613
  rhythmicContrast: 0.8409589286893606
purpose: []
